parameters:
    khatovar_member.controller.member.class: Khatovar\Bundle\MemberBundle\Controller\MemberController

services:
    khatovar_member.controller.member:
        scope: request
        class: %khatovar_member.controller.member.class%
        arguments:
            - '@fos_user.entity_manager'
            - '@session'
        calls:
            - [ setContainer, ['@service_container']]
