khatovar_web_member:
    path:       /
    defaults:   { _controller: 'khatovar_member.controller.member:indexAction' }

khatovar_web_member_show:
    path:       /historique/{slug}
    defaults:   { _controller: 'khatovar_member.controller.member:showAction' }
    requirements:
        slug: "[a-zA-Z0-9-_/]+"

khatovar_web_member_new:
    path:       /new
    defaults:   { _controller: 'khatovar_member.controller.member:newAction' }

khatovar_web_member_create:
    path:       /create
    defaults:   { _controller: 'khatovar_member.controller.member:createAction' }
    methods:  [POST]

khatovar_web_member_edit:
    path:       /{id}/edit
    defaults:   { _controller: 'khatovar_member.controller.member:editAction' }

khatovar_web_member_update:
    path:       /{id}/update
    defaults:   { _controller: 'khatovar_member.controller.member:updateAction' }
    methods:  [POST, PUT]

khatovar_web_member_delete:
    path:       /{id}/delete
    defaults:   { _controller: 'khatovar_member.controller.member:deleteAction' }
    methods:  [POST, DELETE]
