carcel_documents_homepage:
    pattern:  /{folder}
    defaults: { _controller: CarcelDocumentsBundle:Documents:index, folder: 0 }
    requirements:
        folder: \d*

carcel_documents_share:
    pattern: /share/{file}
    defaults: { _controller: CarcelDocumentsBundle:Documents:share }
    requirements:
        file: \d+

carcel_documents_add_folder:
    pattern: /addFolder/{parent}
    defaults: { _controller: CarcelDocumentsBundle:Documents:addFolder }
    requirements:
        parent: \d+

carcel_documents_add_file:
    pattern: /addFile/{folder}
    defaults: { _controller: CarcelDocumentsBundle:Documents:addFile }
    requirements:
        folder: \d+

carcel_documents_move_folder:
    pattern: /moveFolder/{folder}
    defaults: { _controller: CarcelDocumentsBundle:Documents:moveFolder }
    requirements:
        folder: \d+

carcel_documents_move_file:
    pattern: /moveFile/{file}
    defaults: { _controller: CarcelDocumentsBundle:Documents:moveFile }
    requirements:
        file: \d+

carcel_documents_rename_folder:
    pattern: /renameFolder/{folder}
    defaults: { _controller: CarcelDocumentsBundle:Documents:renameFolder }
    requirements:
        folder: \d+

carcel_documents_rename_file:
    pattern: /renameFile/{file}
    defaults: { _controller: CarcelDocumentsBundle:Documents:renameFile }
    requirements:
        file: \d+

carcel_documents_remove_folder:
    pattern: /removeFolder/{folder}
    defaults: { _controller: CarcelDocumentsBundle:Documents:removeFolder }
    requirements:
        folder: \d+

carcel_documents_remove_file:
    pattern: /removeFile/{file}
    defaults: { _controller: CarcelDocumentsBundle:Documents:removeFile }
    requirements:
        file: \d+
