imports:
    - { resource: config_dev.yml }
    - { resource: ../../tests/end-to-end/Resources/config/services.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: true

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
