fos_user:
    resource: '@FOSUserBundle/Resources/config/routing/all.xml'

khatovar_user:
    resource: '@KhatovarUserBundle/Resources/config/routing.yml'
    prefix:   /

khatovar_web:
    resource: '@KhatovarWebBundle/Resources/config/routing.yml'
    prefix:   /

khatovar_documents:
    resource: '@KhatovarDocumentsBundle/Resources/config/routing.yml'
    prefix:   /documents

# redirecting the root
root:
    path: /
    defaults:
        _controller: 'FrameworkBundle:Redirect:urlRedirect'
        path: /accueil
        permanent: true
