services:
    Khatovar\Component\User\Application\Command\SetRoleHandler:
        arguments:
            - '@Khatovar\Bundle\UserBundle\Repository\Doctrine\UserRepository'
            - '@Khatovar\Component\User\Application\Query\GetUserRoles'

    Khatovar\Component\User\Application\Command\UserStatusHandler:
        arguments:
            - '@Khatovar\Bundle\UserBundle\Repository\Doctrine\UserRepository'
