services:
    Khatovar\Component\User\Application\Command\SetRoleHandler:
        arguments:
            - '@Khatovar\Component\User\Domain\Repository\UserRepositoryInterface'
            - '@Khatovar\Component\User\Application\Query\GetUserRoles'

    Khatovar\Component\User\Application\Command\UserStatusHandler:
        arguments:
            - '@Khatovar\Component\User\Domain\Repository\UserRepositoryInterface'
