services:
    Khatovar\Bundle\UserBundle\EventSubscriber\MailerSubscriber:
        arguments:
            - '@Khatovar\Bundle\UserBundle\Factory\SwiftMessageFactory'
            - '@mailer'
            - '@translator'
            - '%mailer_user%'
        tags:
            - { name: kernel.event_subscriber }
