services:
    khatovar_user.event.subscriber.mailer:
        class: Khatovar\Bundle\UserBundle\EventSubscriber\MailerSubscriber
        arguments:
            - '@mailer'
            - '@translator'
            - '@khatovar_user.factory.swift_message'
            - '%mailer_user%'
        tags:
            - { name: kernel.event_subscriber }
