services:
    khatovar_user.event.subscriber.mailer:
        class: Khatovar\Bundle\UserBundle\EventSubscriber\MailerSubscriber
        arguments:
            - '@khatovar_user.manager.mail'
        tags:
            - { name: kernel.event_subscriber }
