services:
    khatovar_user.factory.user_form:
        class: Khatovar\Bundle\UserBundle\Form\Factory\UserFormFactory
        arguments:
            - '@form.factory'
            - '@router'
            - '@translator'
            - '@Khatovar\Component\User\Application\Query\UserRole'
