services:
    khatovar_user.form.type.user:
        class: Khatovar\Bundle\UserBundle\Form\Type\UserType
        arguments:
            - '@translator'
            - Khatovar\Bundle\UserBundle\Entity\User
        tags:
            - { name: form.type }
