services:
    Khatovar\Bundle\UserBundle\Form\Factory\UserFormFactory:
        arguments:
            - '@form.factory'
            - '@router'
            - '@translator'
            - '@Khatovar\Component\User\Application\Query\GetUserRoles'
