services:
    Khatovar\Component\User\Application\Query\GetUserFromDatabase:
        arguments:
            - '@Khatovar\Bundle\UserBundle\Entity\Repository\UserRepository'
            - '@Khatovar\Bundle\UserBundle\Security\Authentication\UserInSecurityTokenStorage'
