services:
    Khatovar\Bundle\UserBundle\Query\GetUserFromDatabase:
        arguments:
            - '@Khatovar\Bundle\UserBundle\Entity\Repository\UserRepository'
            - '@Khatovar\Bundle\UserBundle\Security\Core\Authentication\Token\Storage\UserInSecurityTokenStorage'
