services:
    Khatovar\Component\User\Application\Query\GetUser:
        arguments:
            - '@Khatovar\Bundle\UserBundle\Repository\Doctrine\UserRepository'
            - '@Khatovar\Bundle\UserBundle\Security\Authentication\UserInSecurityTokenStorage'

    Khatovar\Component\User\Application\Query\GetUserRoles:
        arguments:
            - '@Khatovar\Bundle\UserBundle\Security\Authentication\UserInSecurityTokenStorage'
            - '%security.role_hierarchy.roles%'

    Khatovar\Component\User\Application\Query\GetAdministrableUsers:
        arguments:
            - '@Khatovar\Bundle\UserBundle\Security\Authentication\UserInSecurityTokenStorage'
            - '@Khatovar\Bundle\UserBundle\Repository\Doctrine\UserRepository'
