services:
    Khatovar\Component\User\Domain\Repository\UserRepositoryInterface:
        class: 'Khatovar\Bundle\UserBundle\Repository\Doctrine\UserRepository'
        arguments:
            - '@doctrine'
