<?php

namespace Khatovar\Bundle\ExactionBundle\Entity;

/**
 * ExactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExactionRepository extends \Doctrine\ORM\EntityRepository
{
}
