parameters:
    khatovar_exaction.controller.exaction.class: Khatovar\Bundle\ExactionBundle\Controller\ExactionController

services:
    khatovar_exaction.controller.exaction:
        scope: request
        class: %khatovar_exaction.controller.exaction.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@session'
            - '@khatovar_exaction.manager.exaction'
        calls:
            - [ setContainer, ['@service_container']]
