parameters:
    khatovar_exaction.form.type.exaction.class: Khatovar\Bundle\ExactionBundle\Form\ExactionType

services:
    khatovar_exaction.form.type.exaction:
        class: %khatovar_exaction.form.type.exaction.class%
        tags:
            - { name: form.type, alias: khatovar_exaction_type }
