khatovar_web_exaction_to_come:
    path:     /a_venir
    defaults: { _controller: KhatovarExactionBundle:Exaction:toCome }

khatovar_web_exaction_past:
    path:     /passees
    defaults: { _controller: KhatovarExactionBundle:Exaction:index }

khatovar_web_exaction_list_by_year:
    path:     /passees/{year}
    defaults: { _controller: KhatovarExactionBundle:Exaction:viewByYear }
    requirements:
        year: \d+

khatovar_web_exaction_add:
    path:     /add
    defaults: { _controller: KhatovarExactionBundle:Exaction:add }

khatovar_web_exaction_edit:
    path:     /edit/{exaction}
    defaults: { _controller: KhatovarExactionBundle:Exaction:edit }
    requirements:
        exaction: \d+

khatovar_web_exaction_remove:
    path:     /remove/{exaction}
    defaults: { _controller: KhatovarExactionBundle:Exaction:remove }
    requirements:
        exaction: \d+
