khatovar_web_exaction:
    path:     /
    defaults: { _controller: 'khatovar_exaction.controller.exaction:indexAction' }

khatovar_web_exaction_to_come:
    path:     /a_venir
    defaults: { _controller: 'khatovar_exaction.controller.exaction:toComeAction' }

khatovar_web_exaction_past:
    path:     /passees
    defaults: { _controller: 'khatovar_exaction.controller.exaction:pastAction' }

khatovar_web_exaction_list_by_year:
    path:     /passees/{year}
    defaults: { _controller: 'khatovar_exaction.controller.exaction:viewByYearAction' }

khatovar_web_exaction_new:
    path:     /new
    defaults: { _controller: 'khatovar_exaction.controller.exaction:newAction' }

khatovar_web_exaction_create:
    path:     /create
    defaults: { _controller: 'khatovar_exaction.controller.exaction:createAction' }
    methods:  [POST]

khatovar_web_exaction_edit:
    path:     /{id}/edit
    defaults: { _controller: 'khatovar_exaction.controller.exaction:editAction' }

khatovar_web_exaction_update:
    path:     /{id}/update
    defaults: { _controller: 'khatovar_exaction.controller.exaction:updateAction' }
    methods:  [POST, PUT]

khatovar_web_exaction_delete:
    path:     /{id}/delete
    defaults: { _controller: 'khatovar_exaction.controller.exaction:deleteAction' }
    methods:  [POST, DELETE]
