services:
    khatovar_exaction.twig.normalizer.date:
        class: Khatovar\Bundle\ExactionBundle\Twig\DateNormalizer
        tags:
            - { name: twig.extension }

    khatovar_exaction.twig.normalizer.link:
        class: Khatovar\Bundle\ExactionBundle\Twig\LinkNormalizer
        tags:
            - { name: twig.extension }
