Khatovar\Bundle\ExactionBundle\Entity\Exaction:
    properties:
        name:
            - NotBlank: ~
        place:
            - NotBlank: ~
        links:
            - Khatovar\Bundle\ExactionBundle\Validator\Constraints\ExactionLink: ~
        map:
            - NotBlank: ~
            - Khatovar\Bundle\ExactionBundle\Validator\Constraints\ContainsIframe: ~
            - Khatovar\Bundle\ExactionBundle\Validator\Constraints\IframeSize: ~
    constraints:
        - Khatovar\Bundle\ExactionBundle\Validator\Constraints\Dates: ~
