parameters:
    khatovar_appearance.controller.appearance.class: Khatovar\Bundle\AppearanceBundle\Controller\AppearanceController

services:
    khatovar_appearance.controller.appearance:
        scope: request
        class: %khatovar_appearance.controller.appearance.class%
        arguments:
            - '@fos_user.entity_manager'
            - '@session'
            - '@khatovar_appearance.manager.appearance'
        calls:
            - [ setContainer, ['@service_container']]
