parameters:
    khatovar_appearance.manager.appearance.class: Khatovar\Bundle\AppearanceBundle\Manager\AppearanceManager

services:
    khatovar_appearance.manager.appearance:
        class: %khatovar_appearance.manager.appearance.class%
        arguments:
            - '@fos_user.entity_manager'
