khatovar_web_appearance:
    path:     /
    defaults: { _controller: "khatovar_appearance.controller.appearance:indexAction" }

khatovar_web_appearance_workshop:
    path:     /ateliers
    defaults: { _controller: "khatovar_appearance.controller.appearance:workshopAction" }

khatovar_web_appearance_camp:
    path:     /campement
    defaults: { _controller: "khatovar_appearance.controller.appearance:campAction" }

khatovar_web_appearance_list:
    path:     /list
    defaults: { _controller: "khatovar_appearance.controller.appearance:listAction" }

khatovar_web_appearance_show:
    path:     /prestation/{slug}
    defaults: { _controller: "khatovar_appearance.controller.appearance:showAction" }
    requirements:
        slug: "[a-zA-Z0-9-_/]+"

khatovar_web_appearance_new:
    path:     /new
    defaults: { _controller: "khatovar_appearance.controller.appearance:newAction" }

khatovar_web_appearance_create:
    path:     /create
    defaults: { _controller: "khatovar_appearance.controller.appearance:createAction" }
    methods:  POST

khatovar_web_appearance_edit_index:
    path:     /index/edit
    defaults: { _controller: "khatovar_appearance.controller.appearance:editIndexAction" }

khatovar_web_appearance_edit:
    path:     /{id}/edit
    defaults: { _controller: "khatovar_appearance.controller.appearance:editAction" }

khatovar_web_appearance_update:
    path:     /{id}/update
    defaults: { _controller: "khatovar_appearance.controller.appearance:updateAction" }
    methods:  [POST, PUT]

khatovar_web_appearance_delete:
    path:     /{id}/delete
    defaults: { _controller: "khatovar_appearance.controller.appearance:deleteAction" }
    methods:  [POST, DELETE]
