services:
    khatovar_contact.form.subscriber.add_visit_card:
        class: Khatovar\Bundle\WebBundle\Form\Subscriber\AddVisitCardSubscriber

    khatovar_exaction.form.subscriber.add_passed_exaction_fields:
        class: Khatovar\Bundle\WebBundle\Form\Subscriber\AddPassedExactionFieldsSubscriber

    khatovar_member.form.subscriber.add_portrait:
        class: Khatovar\Bundle\WebBundle\Form\Subscriber\AddPortraitSubscriber

    khatovar_member.form.subscriber.remove_owner:
        class: Khatovar\Bundle\WebBundle\Form\Subscriber\RemoveOwnerSubscriber
        arguments:
            - '@security.token_storage'

    khatovar_photo.form.subscriber.add_fields:
        class: Khatovar\Bundle\WebBundle\Form\Subscriber\AddPhotoFieldsSubscriber

    khatovar_photo.form.subscriber.add_authorized:
        class: Khatovar\Bundle\WebBundle\Form\Subscriber\AddAuthorizedFieldsSubscriber
