services:
    khatovar_contact.handler.contact_activation:
        class: Khatovar\Bundle\WebBundle\Handler\ActivationHandler
        arguments:
            - '@doctrine.orm.entity_manager'
            - 'Khatovar\Bundle\WebBundle\Entity\Contact'

    khatovar_homepage.handler.homepage_activation:
        class: Khatovar\Bundle\WebBundle\Handler\ActivationHandler
        arguments:
            - '@doctrine.orm.entity_manager'
            - 'Khatovar\Bundle\WebBundle\Entity\Homepage'
