services:
    khatovar_appearance.manager.appearance:
        class: Khatovar\Bundle\WebBundle\Manager\AppearanceManager
        arguments:
            - '@doctrine'

    khatovar_exaction.manager.exaction:
        class: Khatovar\Bundle\WebBundle\Manager\ExactionManager
        arguments:
            - '@doctrine'

    khatovar_photo.manager.photo:
        class: Khatovar\Bundle\WebBundle\Manager\PhotoManager
        arguments:
            - '@doctrine'
            - '@security.authorization_checker'
            - '@security.token_storage'
