parameters:
    khatovar_web.manager.photo.class:  Khatovar\Bundle\WebBundle\Manager\KhatovarPhotoManager

services:
    khatovar_web.manager.photo:
        class: %khatovar_web.manager.photo.class%
        arguments:
            - '@doctrine.orm.entity_manager'
