services:
    khatovar_appearance.manager.appearance:
        class: Khatovar\Bundle\WebBundle\Manager\AppearanceManager
        arguments:
            - '@doctrine.orm.entity_manager'

    khatovar_exaction.manager.exaction:
        class: Khatovar\Bundle\WebBundle\Manager\ExactionManager
        arguments:
            - '@doctrine.orm.entity_manager'
