services:
    khatovar_web.menu.menu_builder:
        class: Khatovar\Bundle\WebBundle\Menu\MenuBuilder
        arguments:
            - '@knp_menu.factory'
            - '@doctrine.orm.entity_manager'
            - '@khatovar_exaction.manager.exaction'

    khatovar_web.menu.main:
        class: Knp\Menu\MenuItem
        factory: ['@khatovar_web.menu.menu_builder', createMainMenu]
        arguments: ['@request_stack']
        tags:
            - { name: knp_menu.menu, alias: main }
