khatovar_web_camp:
    path:     /camp
    defaults: { _controller: KhatovarWebBundle:Web:camp }

khatovar_appearance:
    resource: '@KhatovarWebBundle/Resources/config/routing/appearance.yml'
    prefix:   /prestations

khatovar_contact:
    resource: '@KhatovarWebBundle/Resources/config/routing/contact.yml'
    prefix:   /contact
