
khatovar_web_camp:
    path:       /camp/{atelier}
    defaults:   { _controller: KhatovarWebBundle:Default:camp, atelier: 'introduction' }
    requirements:
        atelier: \w*

khatovar_web_fight:
    path:       /combat/{pratique}
    defaults:   { _controller: KhatovarWebBundle:Default:fight, pratique: 'introduction' }
    requirements:
        pratique: \w*

khatovar_web_links:
    path:       /liens/{contact}
    defaults:   { _controller: KhatovarWebBundle:Default:links, contact: 'liste' }
    requirements:
        contact: \w*
