parameters:
    khatovar.web.twig.khatovar_photos_extension.class: Khatovar\Bundle\WebBundle\Services\Twig\KhatovarPhotosExtension
    khatovar.web.twig.controller_name_extension.class: Khatovar\Bundle\WebBundle\Services\Twig\ControllerNameExtension
    khatovar.web.filters.translation.class:            Khatovar\Bundle\WebBundle\Services\Filters\KhatovarTranslation
    khatovar.web.filter.image_resize.class:                Khatovar\Bundle\WebBundle\Services\Filters\KhatovarImageResize
    khatovar.web.filters.return_array.class:           Khatovar\Bundle\WebBundle\Services\Filters\KhatovarReturnArray
    khatovar.web.menu.menu_builder.class:              Khatovar\Bundle\WebBundle\Menu\MenuBuilder
    khatovar.web.menu.main.class:                      Knp\Menu\MenuItem

services:
    khatovar.web.twig.khatovar_photos_extension:
        class: %khatovar.web.twig.khatovar_photos_extension.class%
        tags:
            - { name: twig.extension }

    khatovar.web.twig.controller_name_extension:
        class: %khatovar.web.twig.controller_name_extension.class%
        calls:
            - [setRequest, ['@?request=']]
        tags:
            - { name: twig.extension }

    khatovar.web.filters.translation:
        class: %khatovar.web.filters.translation.class%
        arguments:
            - '@doctrine.orm.entity_manager'

    khatovar.web.filter.image_resize:
        class: %khatovar.web.filter.image_resize.class%

    khatovar.web.filters.return_array:
        class: %khatovar.web.filters.return_array.class%
        arguments:
            - '@doctrine.orm.entity_manager'

    khatovar.web.menu.menu_builder:
        class: %khatovar.web.menu.menu_builder.class%
        arguments:
            - '@knp_menu.factory'
            - '@khatovar_exaction.manager.exaction'

    khatovar.web.menu.main:
        class: %khatovar.web.menu.main.class%
        factory_service: khatovar.web.menu.menu_builder
        factory_method: createMainMenu
        arguments:
            - '@request'
        scope: request
        tags:
            - { name: knp_menu.menu, alias: main }
