services:
    khatovar_web.twig.photo:
        class: Khatovar\Bundle\WebBundle\Twig\PhotosExtension
        tags:
            - { name: twig.extension }

    khatovar_web.twig.controller_name:
        class: Khatovar\Bundle\WebBundle\Twig\ControllerNameExtension
        arguments:
            - '@request_stack'
        tags:
            - { name: twig.extension }

    khatovar_web.twig.side_panel:
        class: Khatovar\Bundle\WebBundle\Twig\SidePanelExtension
        arguments:
            - '@khatovar_photo.manager.photo'
        tags:
            - { name: twig.extension }
