services:
    khatovar_web.twig.photo:
        class: Khatovar\Bundle\WebBundle\Twig\PhotosExtension
        tags:
            - { name: twig.extension }

    khatovar_web.twig.controller_name:
        class: Khatovar\Bundle\WebBundle\Twig\ControllerNameExtension
        arguments:
            - '@request_stack'
        tags:
            - { name: twig.extension }

    khatovar_web.twig.side_panel:
        class: Khatovar\Bundle\WebBundle\Twig\SidePanelExtension
        arguments:
            - '@khatovar_photo.manager.photo'
        tags:
            - { name: twig.extension }

    khatovar_appearance.twig.normalizer.link:
        class: Khatovar\Bundle\WebBundle\Twig\AppearanceLinkNormalizer
        arguments:
            - '@router'
        tags:
            - { name: twig.extension }

    khatovar_exaction.twig.normalizer.date:
        class: Khatovar\Bundle\WebBundle\Twig\DateNormalizer
        tags:
            - { name: twig.extension }

    khatovar_exaction.twig.normalizer.link:
        class: Khatovar\Bundle\WebBundle\Twig\ExactionLinkNormalizer
        tags:
            - { name: twig.extension }
