khatovar_web_homepage:
    path:       /accueil
    defaults:   { _controller: KhatovarWebBundle:Homepage:index }

khatovar_web_homepage_create:
    path:       /accueil/create
    defaults:   { _controller: KhatovarWebBundle:Homepage:create }

khatovar_web_homepage_edit:
    path:       /accueil/edit/{homepage}
    defaults:   { _controller: KhatovarWebBundle:Homepage:edit }
    requirements:
        homepage: \d+

khatovar_web_homepage_list:
    path:       /accueil/list
    defaults:   { _controller: KhatovarWebBundle:Homepage:list }

khatovar_web_homepage_delete:
    path:       /accueil/delete/{homepage}
    defaults:   { _controller: KhatovarWebBundle:Homepage:delete }
    requirements:
        homepage: \d+



khatovar_web_photos:
    path:       /photos
    defaults:   { _controller: KhatovarWebBundle:Photo:index }

khatovar_web_photos_add:
    path:       /photos/add
    defaults:   { _controller: KhatovarWebBundle:Photo:add }

khatovar_web_photos_edit:
    path:       /photos/edit/{photo}
    defaults:   { _controller: KhatovarWebBundle:Photo:edit }
    requirements:
        photo: \d+

khatovar_web_photos_delete:
    path:       /photos/delete/{photo}
    defaults:   { _controller: KhatovarWebBundle:Photo:delete }
    requirements:
        photo: \d+



khatovar_web_camp:
    path:       /camp/{atelier}
    defaults:   { _controller: KhatovarWebBundle:Default:camp, atelier: 'introduction' }
    requirements:
        atelier: \w*

khatovar_web_fight:
    path:       /combat/{pratique}
    defaults:   { _controller: KhatovarWebBundle:Default:fight, pratique: 'introduction' }
    requirements:
        pratique: \w*

khatovar_web_schedule:
    path:       /programmation
    defaults:   { _controller: KhatovarWebBundle:Default:schedule }

khatovar_web_references:
    path:       /references/{year}
    defaults:   { _controller: KhatovarWebBundle:Default:references, year: 0 }
    requirements:
        year: \d*

khatovar_web_members:
    path:       /membres/{name}
    defaults:   { _controller: KhatovarWebBundle:Default:members, name: 'liste' }
    requirements:
        name: \w*

khatovar_web_links:
    path:       /liens/{contact}
    defaults:   { _controller: KhatovarWebBundle:Default:links, contact: 'liste' }
    requirements:
        contact: \w*
