parameters:
#    khatovar_web.example.class: Khatovar\WebBundle\Example

services:
    khatovar.twig.khatovar_extension:
        class: Khatovar\WebBundle\Services\Twig\KhatovarExtension
        tags:
            - { name: twig.extension }

    khatovar.twig.controller_name_extension:
        class: Khatovar\WebBundle\Services\Twig\ControllerNameExtension
        calls:
            - [setRequest, ["@?request="]]
        tags:
            - { name: twig.extension }

    khatovar.filters.translation:
        class: Khatovar\WebBundle\Services\Filters\KhatovarTranslation
        arguments: [ "@doctrine.orm.entity_manager" ]

    khatovar.filter.resize:
        class: Khatovar\WebBundle\Services\Filters\KhatovarImageResize

    khatovar.filters.array:
        class: Khatovar\WebBundle\Services\Filters\KhatovarReturnArray
        arguments: [ "@doctrine.orm.entity_manager" ]

    khatovar.menu.menu_builder:
        class: Khatovar\WebBundle\Menu\MenuBuilder
        arguments: [ "@knp_menu.factory" ]

    khatovar.menu.main:
        class: Knp\Menu\MenuItem
        factory_service: khatovar.menu.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: main }
