parameters:
#    khatovar_web.example.class: Khatovar\WebBundle\Example

services:
    khatovar.twig.khatovar_extension:
        class: Khatovar\WebBundle\Services\Twig\KhatovarExtension
        tags:
            - { name: twig.extension }

    khatovar.code.translation:
        class: Khatovar\WebBundle\Services\Translation\KhatovarTranslation

    khatovar.twig.controller_name_extension:
        class: Khatovar\WebBundle\Services\Twig\ControllerNameExtension
        calls:
            - [setRequest, ["@?request="]]
        tags:
            - { name: twig.extension }
