parameters:
#    khatovar_web.example.class: Khatovar\WebBundle\Example

services:
    khatovar.twig.khatovar_extension:
        class: Khatovar\WebBundle\Services\Twig\KhatovarExtension
        tags:
            - { name: twig.extension }

    khatovar.twig.controller_name_extension:
        class: Khatovar\WebBundle\Services\Twig\ControllerNameExtension
        calls:
            - [setRequest, ["@?request="]]
        tags:
            - { name: twig.extension }

    khatovar.filters.translation:
        class: Khatovar\WebBundle\Services\Filters\KhatovarTranslation
        arguments: [ "@doctrine.orm.entity_manager" ]

    khatovar.filter.resize:
        class: Khatovar\WebBundle\Services\Filters\KhatovarImageResize
