<?php

namespace Khatovar\WebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HomepageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HomepageRepository extends EntityRepository
{
}
