parameters:
    khatovar_homepage.controller.homepage.class: Khatovar\Bundle\HomepageBundle\Controller\HomepageController

services:
    khatovar_homepage.controller.homepage:
        scope: request
        class: %khatovar_homepage.controller.homepage.class%
        arguments:
            - '@service_container'
            - '@doctrine.orm.entity_manager'
