services:
    khatovar_homepage.form.type.homepage:
        class: Khatovar\Bundle\HomepageBundle\Form\Type\HomepageType
        tags:
            - { name: form.type }

    khatovar_homepage.form.type.homepage_activation:
        class: Khatovar\Bundle\HomepageBundle\Form\Type\HomepageActivationType
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: form.type }
