services:
    khatovar_homepage.form.handler.homepage_activation:
        class: Khatovar\Bundle\WebBundle\Form\Handler\ActivationHandler
        arguments:
            - '@doctrine.orm.entity_manager'
            - 'Khatovar\Bundle\HomepageBundle\Entity\Homepage'
