khatovar_web_homepage:
    path:       /
    defaults:   { _controller: 'khatovar_homepage.controller.homepage:indexAction' }

khatovar_web_homepage_show:
    path:       /{id}/show
    defaults:   { _controller: 'khatovar_homepage.controller.homepage:showAction' }

khatovar_web_homepage_list:
    path:       /list
    defaults:   { _controller: 'khatovar_homepage.controller.homepage:listAction' }

khatovar_web_homepage_new:
    path:       /new
    defaults:   { _controller: 'khatovar_homepage.controller.homepage:newAction' }

khatovar_web_homepage_create:
    path:       /create
    defaults:   { _controller: 'khatovar_homepage.controller.homepage:createAction' }
    methods:  [POST]

khatovar_web_homepage_edit:
    path:       /{id}/edit
    defaults:   { _controller: 'khatovar_homepage.controller.homepage:editAction' }

khatovar_web_homepage_update:
    path:       /{id}/update
    defaults:   { _controller: 'khatovar_homepage.controller.homepage:updateAction' }
    methods:  [POST, PUT]

khatovar_web_homepage_delete:
    path:       /{id}/delete
    defaults:   { _controller: 'khatovar_homepage.controller.homepage:deleteAction' }
    methods:  [POST, DELETE]
