khatovar_web_homepage:
    path:       /
    defaults:   { _controller: KhatovarHomepageBundle:Homepage:index }

khatovar_web_homepage_create:
    path:       /create
    defaults:   { _controller: KhatovarHomepageBundle:Homepage:create }

khatovar_web_homepage_edit:
    path:       /edit/{homepage}
    defaults:   { _controller: KhatovarHomepageBundle:Homepage:edit }
    requirements:
        homepage: \d+

khatovar_web_homepage_list:
    path:       //list
    defaults:   { _controller: KhatovarHomepageBundle:Homepage:list }

khatovar_web_homepage_delete:
    path:       /delete/{homepage}
    defaults:   { _controller: KhatovarHomepageBundle:Homepage:delete }
    requirements:
        homepage: \d+
