Khatovar\Bundle\HomepageBundle\Entity\Homepage:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
    properties:
        name:
            - NotBlank: ~
            - Length:
                max: 255
        content:
            - NotBlank: ~
