parameters:
    khatovar_contact.controller.contact.class: Khatovar\Bundle\ContactBundle\Controller\ContactController

services:
    khatovar_contact.controller.contact:
        scope: request
        class: %khatovar_contact.controller.contact.class%
        arguments:
            - '@fos_user.entity_manager'
            - '@session'
        calls:
            - [ setContainer, ['@service_container']]
