fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

carcel_user_admin:
    pattern: /admin
    defaults: { _controller: "CarcelUserBundle:Admin:index" }

carcel_user_admin_show:
    pattern: /admin/show/{user}
    defaults: { _controller: "CarcelUserBundle:Admin:showProfile" }
    requirements:
        user: \d+

carcel_user_admin_edit:
    pattern: /admin/edit/{user}
    defaults: { _controller: "CarcelUserBundle:Admin:editProfile" }
    requirements:
        user: \d+

carcel_user_admin_set_role:
    pattern: /admin/role/{user}
    defaults: { _controller: "CarcelUserBundle:Admin:setRole" }
    requirements:
        user: \d+

carcel_user_admin_remove:
    pattern: /admin/remove/{user}
    defaults: { _controller: "CarcelUserBundle:Admin:removeUser" }
    requirements:
        user: \d+
