services:
    khatovar_documents.factory.file:
        class: Khatovar\Bundle\DocumentsBundle\Factory\FileFactory
        arguments:
            - '@khatovar_documents.repositories.folder'
            - '%khatovar_document.upload_dir%'

    khatovar_documents.factory.folder:
        class: Khatovar\Bundle\DocumentsBundle\Factory\FolderFactory
        arguments:
            - '@khatovar_documents.repositories.folder'
