parameters:
    khatovar_documents.form.subscriber.add_parent.class: Khatovar\Bundle\DocumentsBundle\Form\Subscriber\AddParentSubscriber
    khatovar_documents.form.subscriber.file.class: Khatovar\Bundle\DocumentsBundle\Form\Subscriber\FileSubscriber

services:
    khatovar_documents.form.subscriber.add_parent:
        class: Khatovar\Bundle\DocumentsBundle\Form\Subscriber\AddParentSubscriber
        arguments:
            - '@translator'
            - '@khatovar_documents.repositories.folder'

    khatovar_documents.form.subscriber.file:
        class: Khatovar\Bundle\DocumentsBundle\Form\Subscriber\FileSubscriber
        arguments:
            - '@translator'
