services:
    khatovar_documents.form.type.folder:
        class: Khatovar\Bundle\DocumentsBundle\Form\Type\FolderType
        arguments:
            - '@translator'
        tags:
            - { name: form.type }

    khatovar_documents.form.type.file:
        class: Khatovar\Bundle\DocumentsBundle\Form\Type\FileType
        arguments:
            - '@translator'
        tags:
            - { name: form.type }

    khatovar_documents.form.type.move_folder:
        class: Khatovar\Bundle\DocumentsBundle\Form\Type\FolderMoveType
        arguments:
            - '@translator'
            - '@khatovar_documents.repositories.folder'
            - '@khatovar_documents.form.data_transformer.folder_to_number'
        tags:
            - { name: form.type }

    khatovar_documents.form.type.move_file:
        class: Khatovar\Bundle\DocumentsBundle\Form\Type\FileMoveType
        arguments:
            - '@translator'
            - '@khatovar_documents.repositories.folder'
            - '@khatovar_documents.form.data_transformer.folder_to_number'
        tags:
            - { name: form.type }
