services:
    khatovar_documents.repositories.folder:
        class: Khatovar\Bundle\DocumentsBundle\Entity\FolderRepository
        factory: ['@doctrine', getRepository]
        arguments:
            - 'KhatovarDocumentsBundle:Folder'

    khatovar_documents.repositories.file:
        class: Khatovar\Bundle\DocumentsBundle\Entity\FileRepository
        factory: ['@doctrine', getRepository]
        arguments:
            - 'KhatovarDocumentsBundle:File'
