parameters:
    khatovar_photo.controller.photo.class: Khatovar\Bundle\PhotoBundle\Controller\PhotoController

services:
    khatovar_photo.controller.photo:
        scope: request
        class: %khatovar_photo.controller.photo.class%
        arguments:
            - '@fos_user.entity_manager'
            - '@session'
            - '@khatovar_photo.manager.photo'
        calls:
            - [ setContainer, ['@service_container']]
