services:
    khatovar_photo.form.subscriber.add_fields:
        class: Khatovar\Bundle\PhotoBundle\Form\Subscriber\AddPhotoFieldsSubscriber

    khatovar_photo.form.subscriber.add_authorized:
        class: Khatovar\Bundle\PhotoBundle\Form\Subscriber\AddAuthorizedFieldsSubscriber
