khatovar_web_photos:
    path:       /
    defaults:   { _controller: KhatovarPhotoBundle:Photo:index }

khatovar_web_photos_add:
    path:       /add
    defaults:   { _controller: KhatovarPhotoBundle:Photo:add }

khatovar_web_photos_edit:
    path:       /edit/{photo}
    defaults:   { _controller: KhatovarPhotoBundle:Photo:edit }
    requirements:
        photo: \d+

khatovar_web_photos_delete:
    path:       /delete/{photo}
    defaults:   { _controller: KhatovarPhotoBundle:Photo:delete }
    requirements:
        photo: \d+
