khatovar_web_photo:
    path:       /
    defaults:   { _controller: 'khatovar_photo.controller.photo:indexAction' }

khatovar_web_photo_new:
    path:       /new
    defaults:   { _controller: 'khatovar_photo.controller.photo:newAction' }

khatovar_web_photo_create:
    path:     /create
    defaults: { _controller: 'khatovar_photo.controller.photo:createAction' }
    methods:  [POST]

khatovar_web_photo_edit:
    path:       /{id}/edit
    defaults:   { _controller: 'khatovar_photo.controller.photo:editAction' }

khatovar_web_photo_update:
    path:     /{id}/update
    defaults: { _controller: 'khatovar_photo.controller.photo:updateAction' }
    methods:  [POST, PUT]

khatovar_web_photo_delete:
    path:       /{id}/delete
    defaults:   { _controller: 'khatovar_photo.controller.photo:deleteAction' }
    methods:  [POST, DELETE]
